### ISSUE TITLE
ETIMEDOUT on Metro M4 AirLift Lite

### ISSUE THREAD

**Issue by sam-k0** [adafruit/Adafruit_CircuitPython_Requests#203]
Hello adafruit community,
I am following the guide on how to connect / request here:
[https://learn.adafruit.com/adafruit-metro-m4-express-airlift-wifi/internet-connect-2](https://learn.adafruit.com/adafruit-metro-m4-express-airlift-wifi/internet-connect-2)
I am using CircuitPython Version 9.1.1 and the onboard ESP has firmware ver. 1.2.2

And it works fine, connects to my wifi, gets an ip address, can ping google etc. but times out with this error:
```Traceback (most recent call last):
  File "code.py", line 76, in <module>
  File "adafruit_requests.py", line 701, in get
  File "adafruit_requests.py", line 647, in request
  File "adafruit_esp32spi/adafruit_esp32spi_socketpool.py", line 140, in recv
  File "adafruit_esp32spi/adafruit_esp32spi_socketpool.py", line 185, in recv_into
OSError: [Errno 116] ETIMEDOUT
```

Relevant source:
```python
print("Fetching text from", TEXT_URL)
r = requests.get(TEXT_URL)
print("-" * 40)
print(r.text)
print("-" * 40)
r.close()
```

I don't understand why it wouldn't work when it clearly can ping google and even poll adafruit for their ip address.
Any help appreciated.

**Comment by justmobilize** [comment]
`firmware ver. 1.2.2` will have really old certs. Can you please update to the most recent version - instructions [here](https://learn.adafruit.com/upgrading-esp32-firmware/overview) and try again?

**Comment by dhalbert** [comment]
Also, did you change `TEXT_URL`, and if so, what is the new one?

**Comment by sam-k0** [comment]
> Also, did you change `TEXT_URL`, and if so, what is the new one?

Nope, no change from the tutorial, using the adafruit wifi test url. But I'm currently trying to update the esp firmware, maybe that will solve it :+1:

**Comment by sam-k0** [comment]
> `firmware ver. 1.2.2` will have really old certs. Can you please update to the most recent version - instructions [here](https://learn.adafruit.com/upgrading-esp32-firmware/overview) and try again?

I just updated the firmware to 1.7.7, and unfortunately the error persists.

**Comment by axelmagnus** [comment]
Try 4.1.9 of adafruit_request and put in the root. The frozen might be old. pyportal is 4.1.5 .eg. and that worked for me.
