### ISSUE TITLE
OSError 0 with MagTag

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_Requests#51]
I was running code to fetch bitcoin and came across this mysterious error.

```
Traceback (most recent call last):
  File "code.py", line 82, in <module>
  File "code.py", line 74, in <module>
  File "/lib/adafruit_requests.py", line 585, in get
  File "/lib/adafruit_requests.py", line 563, in request
  File "/lib/adafruit_requests.py", line 423, in _get_socket
OSError: 0
```

**Comment by tannewt** [comment]
Moving this to CircuitPython. For any issues on an S2 please file them there first.
