### ISSUE TITLE
non-TLS HTTP requests fail

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_CircuitPython_Requests#71]
Opening this as a fresh issue since #63 should get closed by #70.

On CicruitPython (since PR#4049), non-TLS HTTP requests fail:
```
import sys
import time
import socketpool
# import ssl
import wifi
import secrets
import adafruit_requests as requests
from secrets import secrets

wifi.radio.connect(secrets["ssid"], secrets["password"])
print("RSSI", wifi.radio.ap_info.rssi)

socket = socketpool.SocketPool(wifi.radio)
# http = requests.Session(socket, ssl.create_default_context())  # this doesn't work now for HTTP
http = requests.Session(socket)

URL = "http://wifitest.adafruit.com/testwifi/index.html"  # doesn't work
# URL = "http://httpbin.org/get"  #  doesn't work
# URL = "https://httpbin.org/get"  # works

while True:
    print("-" * 40)
    try:
        response = http.get(URL)
    except (OSError) as e:
        sys.print_exception(e)
    except (RuntimeError) as e:
        sys.print_exception(e)
    try:
        print(response.status_code, response.reason)
        trash = response.text
        trash = None
        response.close()
    except (NameError) as e:
        sys.print_exception(e)
    time.sleep(5)
```
results in:
```
        Traceback (most recent call last):
          File "code.py", line 26, in <module>
          File "code.py", line 24, in <module>
          File "/lib/adafruit_requests.py", line 597, in get
          File "/lib/adafruit_requests.py", line 560, in request
          File "/lib/adafruit_requests.py", line 429, in _get_socket
        RuntimeError: Sending request failed
```

**Comment by anecdata** [comment]
Now, using the build artifact from https://github.com/adafruit/circuitpython/pull/4138, the behavior is `OutOfRetries`, indicating that something is going wrong prior to getting the first good byte back from the socket (the "H" from "HTTP/1.1").

@Neradoc had a working manual example of HTTP without Requests on Discord, so comparing that to Requests and putting in a ton of print-debugs, looks like the issue is that Socket `recv_into()` returns an extra null byte at the end. So this [code](https://github.com/adafruit/Adafruit_CircuitPython_Requests/blob/7b1fc6fd9269318bda3996476b4ecf9fc8f37881/adafruit_requests.py#L572) from Requests:
```
                else:
                    result = bytearray(1)
                    socket.recv_into(result)
                if result == b"H":
```
`result` is:
```
bytearray(b'\x00')
```
but adjusting it to:
```
                else:
                    result = bytearray(2)
                    socket.recv_into(result)
```
`result` is:
```
bytearray(b'H\x00')
```
Still not sure where the null byte comes from, and threfore what the best resolution is.

**Comment by anecdata** [comment]
While poking around, also noticed that this block:
[https://github.com/adafruit/Adafruit_CircuitPython_Requests/blob/7b1fc6fd9269318bda3996476b4ecf9fc8f37881/adafruit_requests.py#L431](https://github.com/adafruit/Adafruit_CircuitPython_Requests/blob/7b1fc6fd9269318bda3996476b4ecf9fc8f37881/adafruit_requests.py#L431)
```
            try:
                sock = self._socket_pool.socket(
                    addr_info[0], addr_info[1], addr_info[2]
                )
            except OSError:
                continue
```
I think has an extra parameter (there used to be three including `proto`, now just `family` and `type`). Doesn't seem to do any harm.
`socketpool_socket_obj_t* common_hal_socketpool_socket(socketpool_socketpool_obj_t* self,
    socketpool_socketpool_addressfamily_t family, socketpool_socketpool_sock_t type);`

**Comment by Neradoc** [comment]
The null byte comes from the buffer being initialized with nulls and not being overwritten because `recv_into` reads one less byte than it should. I believe https://github.com/adafruit/circuitpython/pull/4148 fixes that.
